# Generated by Django 2.2 on 2021-02-28 08:11

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.CharField(max_length=15)),
                ('contact', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('course', models.CharField(choices=[('python', 'Python'), ('django', 'Python Django'), ('js', 'JavaScript')], max_length=250, null=True)),
                ('email', models.CharField(max_length=150, null=True, validators=[account.models.validation_email])),
            ],
        ),
    ]
